### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Overbryd** [liquidz/pipette#3]
Hej,

wanted to know if this package is still alive?

We are currently building an Elixir Flow Based Programming engine, and accidentally, we also named it „Pipette“.

Naming is one of the hardest things in computer science, and we obviously made a mistake.

But before we quickly go for a name change, one question for you:

Would you be up for a name exchange?

Here is what we have built: https://github.com/suitepad-gmbh/pipette

Tell me what you think.

Kind regards,

Lukas Rieder

**Comment by liquidz** [comment]
@Overbryd 
This package is dead, and I can rename or delete this repository.
For the time being, I changed the repository name.

But the package published to hex cannot rename or delete because of hex's restriction.
https://hex.pm/docs/faq

**Comment by Overbryd** [comment]
@liquidz Ok, thanks for the quick response on this. We will keep ours named Pipette then. Thank you so much for letting us use the name.

I wrote an Email to Hex support, lets see what they say about this.

**Comment by Overbryd** [comment]
Here is what they wrote:

> Hi,
> Since you have already established contact with the owners of package pipette could you ask them to transfer ownership of the package to your Hex username? They can add you as package owner with `mix hex.owner` and you'll then remove their ownership. After that's done, please retire all published versions with appropriate message.
> We usually step in when there's no way to contact the other party.

So for the hex package, I think you could add `suitepad` as an owner and we'll retire the currently published versions.

**Comment by liquidz** [comment]
@Overbryd Thanks for your confirmation.
I did `mix hex.owner add pipette engineering@suitepad.de`

**Comment by liquidz** [comment]
@Overbryd How is it going?

**Comment by Overbryd** [comment]
Hi Masashi,

going well. I am finishing up the documentation of the project. Sorry for the slight delay, it took me some time to finish writing the docs and preparing for our release.

You can have a look at the `chore/doc` branch of our repository: https://github.com/suitepad-gmbh/pipette/tree/chore/doc#special-thanks
The README there honours your involvement with a special thanks note.

We are going to push to hex as soon as the [documentation pull request](https://github.com/suitepad-gmbh/pipette/pull/17) is merged.

After that, `pipette` is going to be releases as `0.1.0` from `suitepad-gmbh/pipette` and previous versions will be retired with an appropriate note.

I will update here as soon as everything is finished.

**Comment by Overbryd** [comment]
Again, thank you so much for letting us use the name.
We have published version `{:pipette, "~> 0.1"}` now.

https://hex.pm/packages/pipette

Let me know if you happen to be in or around Berlin, I owe you more than one tea 🍵
